CREATE TABLE "BUILDINGS"
("BUILDING_ID" VARCHAR2(10 BYTE),
"NAME" VARCHAR2(30 BYTE),
"OUTLINE" SDO_GEOMETRY
);

CREATE TABLE "STUDENTS"
("STUDENT_ID" VARCHAR2(10 BYTE),
"LOCATION" SDO_GEOMETRY
);

CREATE TABLE "ANNSYS"
("AS_ID" VARCHAR2(10 BYTE),
"CENTER" SDO_GEOMETRY,
"RADIUS" NUMBER,
"AREA" SDO_GEOMETRY
);

INSERT INTO USER_SDO_GEOM_METADATA VALUES ( 'STUDENTS', 'LOCATION', MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 0, 820, 1 ),MDSYS.SDO_DIM_ELEMENT('Y', 0, 580, 1 ) ), null );
CREATE INDEX STUDENTS_INDEX ON STUDENTS (LOCATION) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

INSERT INTO USER_SDO_GEOM_METADATA VALUES ( 'BUILDINGS', 'OUTLINE', MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 0, 820, 1 ),MDSYS.SDO_DIM_ELEMENT('Y', 0, 580, 1 ) ), null );
CREATE INDEX BUILDINGS_INDEX ON BUILDINGS (OUTLINE) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

INSERT INTO USER_SDO_GEOM_METADATA VALUES ( 'ANNSYS', 'CENTER', MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 0, 820, 1 ),MDSYS.SDO_DIM_ELEMENT('Y', 0, 580, 1 ) ), null );
INSERT INTO USER_SDO_GEOM_METADATA VALUES ( 'ANNSYS', 'AREA', MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 0, 820, 1 ),MDSYS.SDO_DIM_ELEMENT('Y', 0, 580, 1 ) ), null );
CREATE INDEX ANNSYS_CENTER_INDEX ON ANNSYS (CENTER) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX ANNSYS_AREA_INDEX ON ANNSYS (AREA) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE UNIQUE INDEX ANNSYS_ID_INDEX ON ANNSYS (AS_ID);