DELETE FROM USER_SDO_GEOM_METADATA;

DROP INDEX STUDENTS_INDEX;
DROP INDEX BUILDINGS_INDEX;
DROP INDEX ANNSYS_CENTER_INDEX;
DROP INDEX ANNSYS_AREA_INDEX;

DROP TABLE BUILDINGS;
DROP TABLE STUDENTS;
DROP TABLE ANNSYS;